{ _readableState: 
   { highWaterMark: 16384,
     buffer: [],
     length: 0,
     pipes: null,
     pipesCount: 0,
     flowing: false,
     ended: true,
     endEmitted: true,
     reading: false,
     calledRead: true,
     sync: false,
     needReadable: true,
     emittedReadable: false,
     readableListening: false,
     objectMode: false,
     defaultEncoding: 'utf8',
     ranOut: false,
     awaitDrain: 0,
     readingMore: false,
     decoder: null,
     encoding: null },
  readable: false,
  domain: null,
  _events: 
   { end: [ [Function: responseOnEnd], [Function], [Function] ],
     readable: [Function],
     close: [ [Function], [Function] ],
     data: [Function] },
  _maxListeners: 10,
  socket: 
   { _connecting: false,
     _handle: 
      { fd: 12,
        writeQueueSize: 0,
        owner: [Circular],
        onread: [Function: onread],
        reading: true },
     _readableState: 
      { highWaterMark: 16384,
        buffer: [],
        length: 0,
        pipes: null,
        pipesCount: 0,
        flowing: false,
        ended: false,
        endEmitted: false,
        reading: true,
        calledRead: true,
        sync: false,
        needReadable: true,
        emittedReadable: false,
        readableListening: false,
        objectMode: false,
        defaultEncoding: 'utf8',
        ranOut: false,
        awaitDrain: 0,
        readingMore: false,
        decoder: null,
        encoding: null },
     readable: true,
     domain: null,
     _events: 
      { end: [Object],
        finish: [Function: onSocketFinish],
        _socketEnd: [Function: onSocketEnd],
        free: [Function],
        close: [Object],
        agentRemove: [Function],
        drain: [Function: ondrain] },
     _maxListeners: 0,
     _writableState: 
      { highWaterMark: 16384,
        objectMode: false,
        needDrain: false,
        ending: false,
        ended: false,
        finished: false,
        decodeStrings: false,
        defaultEncoding: 'utf8',
        length: 0,
        writing: false,
        sync: false,
        bufferProcessing: false,
        onwrite: [Function],
        writecb: null,
        writelen: 0,
        buffer: [] },
     writable: true,
     allowHalfOpen: false,
     onend: null,
     destroyed: false,
     errorEmitted: false,
     bytesRead: 4503,
     _bytesDispatched: 994,
     _pendingData: null,
     _pendingEncoding: '',
     parser: null,
     _httpMessage: 
      { domain: null,
        _events: [Object],
        _maxListeners: 10,
        output: [],
        outputEncodings: [],
        writable: true,
        _last: false,
        chunkedEncoding: false,
        shouldKeepAlive: true,
        useChunkedEncodingByDefault: true,
        sendDate: false,
        _headerSent: true,
        _header: 'POST /db/data/batch HTTP/1.1\r\nhost: app28070547.sb02.stations.graphenedb.com:24789\r\nauthorization: Basic YXBwMjgwNzA1NDc6cTM4UGx4UlFPckdQN1N5RVplS2k=\r\naccept: application/json\r\ncontent-length: 770\r\nConnection: keep-alive\r\n\r\n',
        _hasBody: true,
        _trailer: '',
        finished: true,
        _hangupClose: false,
        socket: [Circular],
        connection: [Circular],
        agent: [Object],
        socketPath: undefined,
        method: 'POST',
        path: '/db/data/batch',
        _headers: [Object],
        _headerNames: [Object],
        parser: null,
        res: [Circular] },
     ondata: null },
  connection: 
   { _connecting: false,
     _handle: 
      { fd: 12,
        writeQueueSize: 0,
        owner: [Circular],
        onread: [Function: onread],
        reading: true },
     _readableState: 
      { highWaterMark: 16384,
        buffer: [],
        length: 0,
        pipes: null,
        pipesCount: 0,
        flowing: false,
        ended: false,
        endEmitted: false,
        reading: true,
        calledRead: true,
        sync: false,
        needReadable: true,
        emittedReadable: false,
        readableListening: false,
        objectMode: false,
        defaultEncoding: 'utf8',
        ranOut: false,
        awaitDrain: 0,
        readingMore: false,
        decoder: null,
        encoding: null },
     readable: true,
     domain: null,
     _events: 
      { end: [Object],
        finish: [Function: onSocketFinish],
        _socketEnd: [Function: onSocketEnd],
        free: [Function],
        close: [Object],
        agentRemove: [Function],
        drain: [Function: ondrain] },
     _maxListeners: 0,
     _writableState: 
      { highWaterMark: 16384,
        objectMode: false,
        needDrain: false,
        ending: false,
        ended: false,
        finished: false,
        decodeStrings: false,
        defaultEncoding: 'utf8',
        length: 0,
        writing: false,
        sync: false,
        bufferProcessing: false,
        onwrite: [Function],
        writecb: null,
        writelen: 0,
        buffer: [] },
     writable: true,
     allowHalfOpen: false,
     onend: null,
     destroyed: false,
     errorEmitted: false,
     bytesRead: 4503,
     _bytesDispatched: 994,
     _pendingData: null,
     _pendingEncoding: '',
     parser: null,
     _httpMessage: 
      { domain: null,
        _events: [Object],
        _maxListeners: 10,
        output: [],
        outputEncodings: [],
        writable: true,
        _last: false,
        chunkedEncoding: false,
        shouldKeepAlive: true,
        useChunkedEncodingByDefault: true,
        sendDate: false,
        _headerSent: true,
        _header: 'POST /db/data/batch HTTP/1.1\r\nhost: app28070547.sb02.stations.graphenedb.com:24789\r\nauthorization: Basic YXBwMjgwNzA1NDc6cTM4UGx4UlFPckdQN1N5RVplS2k=\r\naccept: application/json\r\ncontent-length: 770\r\nConnection: keep-alive\r\n\r\n',
        _hasBody: true,
        _trailer: '',
        finished: true,
        _hangupClose: false,
        socket: [Circular],
        connection: [Circular],
        agent: [Object],
        socketPath: undefined,
        method: 'POST',
        path: '/db/data/batch',
        _headers: [Object],
        _headerNames: [Object],
        parser: null,
        res: [Circular] },
     ondata: null },
  httpVersion: '1.1',
  complete: true,
  headers: 
   { server: 'nginx',
     date: 'Thu, 12 Mar 2015 02:41:49 GMT',
     'content-type': 'application/json; charset=UTF-8',
     'transfer-encoding': 'chunked',
     connection: 'keep-alive',
     'access-control-allow-origin': '*' },
  trailers: {},
  _pendings: [],
  _pendingIndex: 0,
  url: '',
  method: null,
  statusCode: 200,
  client: 
   { _connecting: false,
     _handle: 
      { fd: 12,
        writeQueueSize: 0,
        owner: [Circular],
        onread: [Function: onread],
        reading: true },
     _readableState: 
      { highWaterMark: 16384,
        buffer: [],
        length: 0,
        pipes: null,
        pipesCount: 0,
        flowing: false,
        ended: false,
        endEmitted: false,
        reading: true,
        calledRead: true,
        sync: false,
        needReadable: true,
        emittedReadable: false,
        readableListening: false,
        objectMode: false,
        defaultEncoding: 'utf8',
        ranOut: false,
        awaitDrain: 0,
        readingMore: false,
        decoder: null,
        encoding: null },
     readable: true,
     domain: null,
     _events: 
      { end: [Object],
        finish: [Function: onSocketFinish],
        _socketEnd: [Function: onSocketEnd],
        free: [Function],
        close: [Object],
        agentRemove: [Function],
        drain: [Function: ondrain] },
     _maxListeners: 0,
     _writableState: 
      { highWaterMark: 16384,
        objectMode: false,
        needDrain: false,
        ending: false,
        ended: false,
        finished: false,
        decodeStrings: false,
        defaultEncoding: 'utf8',
        length: 0,
        writing: false,
        sync: false,
        bufferProcessing: false,
        onwrite: [Function],
        writecb: null,
        writelen: 0,
        buffer: [] },
     writable: true,
     allowHalfOpen: false,
     onend: null,
     destroyed: false,
     errorEmitted: false,
     bytesRead: 4503,
     _bytesDispatched: 994,
     _pendingData: null,
     _pendingEncoding: '',
     parser: null,
     _httpMessage: 
      { domain: null,
        _events: [Object],
        _maxListeners: 10,
        output: [],
        outputEncodings: [],
        writable: true,
        _last: false,
        chunkedEncoding: false,
        shouldKeepAlive: true,
        useChunkedEncodingByDefault: true,
        sendDate: false,
        _headerSent: true,
        _header: 'POST /db/data/batch HTTP/1.1\r\nhost: app28070547.sb02.stations.graphenedb.com:24789\r\nauthorization: Basic YXBwMjgwNzA1NDc6cTM4UGx4UlFPckdQN1N5RVplS2k=\r\naccept: application/json\r\ncontent-length: 770\r\nConnection: keep-alive\r\n\r\n',
        _hasBody: true,
        _trailer: '',
        finished: true,
        _hangupClose: false,
        socket: [Circular],
        connection: [Circular],
        agent: [Object],
        socketPath: undefined,
        method: 'POST',
        path: '/db/data/batch',
        _headers: [Object],
        _headerNames: [Object],
        parser: null,
        res: [Circular] },
     ondata: null },
  _consuming: true,
  _dumped: false,
  httpVersionMajor: 1,
  httpVersionMinor: 1,
  upgrade: false,
  req: 
   { domain: null,
     _events: { error: [Function], drain: [Function] },
     _maxListeners: 10,
     output: [],
     outputEncodings: [],
     writable: true,
     _last: false,
     chunkedEncoding: false,
     shouldKeepAlive: true,
     useChunkedEncodingByDefault: true,
     sendDate: false,
     _headerSent: true,
     _header: 'POST /db/data/batch HTTP/1.1\r\nhost: app28070547.sb02.stations.graphenedb.com:24789\r\nauthorization: Basic YXBwMjgwNzA1NDc6cTM4UGx4UlFPckdQN1N5RVplS2k=\r\naccept: application/json\r\ncontent-length: 770\r\nConnection: keep-alive\r\n\r\n',
     _hasBody: true,
     _trailer: '',
     finished: true,
     _hangupClose: false,
     socket: 
      { _connecting: false,
        _handle: [Object],
        _readableState: [Object],
        readable: true,
        domain: null,
        _events: [Object],
        _maxListeners: 0,
        _writableState: [Object],
        writable: true,
        allowHalfOpen: false,
        onend: null,
        destroyed: false,
        errorEmitted: false,
        bytesRead: 4503,
        _bytesDispatched: 994,
        _pendingData: null,
        _pendingEncoding: '',
        parser: null,
        _httpMessage: [Circular],
        ondata: null },
     connection: 
      { _connecting: false,
        _handle: [Object],
        _readableState: [Object],
        readable: true,
        domain: null,
        _events: [Object],
        _maxListeners: 0,
        _writableState: [Object],
        writable: true,
        allowHalfOpen: false,
        onend: null,
        destroyed: false,
        errorEmitted: false,
        bytesRead: 4503,
        _bytesDispatched: 994,
        _pendingData: null,
        _pendingEncoding: '',
        parser: null,
        _httpMessage: [Circular],
        ondata: null },
     agent: 
      { domain: null,
        _events: [Object],
        _maxListeners: 10,
        options: {},
        requests: {},
        sockets: [Object],
        maxSockets: 5,
        createConnection: [Function] },
     socketPath: undefined,
     method: 'POST',
     path: '/db/data/batch',
     _headers: 
      { host: 'app28070547.sb02.stations.graphenedb.com:24789',
        authorization: 'Basic YXBwMjgwNzA1NDc6cTM4UGx4UlFPckdQN1N5RVplS2k=',
        accept: 'application/json',
        'content-length': 770 },
     _headerNames: 
      { host: 'host',
        authorization: 'authorization',
        accept: 'accept',
        'content-length': 'content-length' },
     parser: null,
     res: [Circular] },
  pipe: [Function],
  addListener: [Function],
  on: [Function],
  pause: [Function],
  resume: [Function],
  read: [Function],
  request: 
   { domain: null,
     _events: 
      { error: [Function],
        complete: [Function],
        pipe: [Function],
        end: [Object],
        data: [Function] },
     _maxListeners: 10,
     readable: true,
     writable: true,
     method: 'POST',
     body: k<Buffer 5b 7b 22 6d 65 74 68 6f 64 22 3a 22 50 4f 53 54 22 2c 22 74 6f 22 3a 22 2f 63 79 70 68 65 72 3f 69 6e 63 6c 75 64 65 53 74 61 74 73 3d 74 72 75 65 22 2c ...>,
     uri: 
      { protocol: 'http:',
        slashes: true,
        auth: 'app28070547:q38PlxRQOrGP7SyEZeKi',
        host: 'app28070547.sb02.stations.graphenedb.com:24789',
        port: '24789',
        hostname: 'app28070547.sb02.stations.graphenedb.com',
        hash: null,
        search: null,
        query: null,
        pathname: '/db/data/batch',
        path: '/db/data/batch',
        href: 'http://app28070547:q38PlxRQOrGP7SyEZeKi@app28070547.sb02.stations.graphenedb.com:24789/db/data/batch' },
     callback: [Function],
     explicitMethod: true,
     canTunnel: 
      { httpOverHttp: [Function: httpOverHttp],
        httpsOverHttp: [Function: httpsOverHttp],
        httpOverHttps: [Function: httpOverHttps],
        httpsOverHttps: [Function: httpsOverHttps],
        debug: [Function] },
     localAddress: undefined,
     pool: {},
     dests: [],
     __isRequestRequest: true,
     _callback: [Function],
     proxy: null,
     _redirectsFollowed: 0,
     maxRedirects: 10,
     followRedirect: true,
     followAllRedirects: false,
     redirects: [],
     headers: 
      { authorization: 'Basic YXBwMjgwNzA1NDc6cTM4UGx4UlFPckdQN1N5RVplS2k=',
        accept: 'application/json',
        'content-length': 770 },
     setHost: true,
     originalCookieHeader: undefined,
     _disableCookies: true,
     _jar: undefined,
     port: '24789',
     host: 'app28070547.sb02.stations.graphenedb.com',
     clientErrorHandler: [Function],
     _parserErrorHandler: [Function],
     _buildRequest: [Function],
     _handleUnixSocketURI: [Function],
     path: '/db/data/batch',
     _user: 'app28070547',
     _pass: 'q38PlxRQOrGP7SyEZeKi',
     _hasAuth: true,
     _sentAuth: true,
     _json: true,
     httpModule: 
      { parsers: [Object],
        STATUS_CODES: [Object],
        IncomingMessage: [Object],
        OutgoingMessage: [Object],
        ServerResponse: [Object],
        Agent: [Object],
        globalAgent: [Object],
        ClientRequest: [Object],
        request: [Function],
        get: [Function],
        Server: [Object],
        createServer: [Function],
        _connectionListener: [Function: connectionListener],
        Client: [Function: deprecated],
        createClient: [Function: deprecated] },
     agentClass: { [Function: Agent] super_: [Object], defaultMaxSockets: 5 },
     agent: 
      { domain: null,
        _events: [Object],
        _maxListeners: 10,
        options: {},
        requests: {},
        sockets: [Object],
        maxSockets: 5,
        createConnection: [Function] },
     _started: true,
     href: 'http://app28070547:q38PlxRQOrGP7SyEZeKi@app28070547.sb02.stations.graphenedb.com:24789/db/data/batch',
     req: 
      { domain: null,
        _events: [Object],
        _maxListeners: 10,
        output: [],
        outputEncodings: [],
        writable: true,
        _last: false,
        chunkedEncoding: false,
        shouldKeepAlive: true,
        useChunkedEncodingByDefault: true,
        sendDate: false,
        _headerSent: true,
        _header: 'POST /db/data/batch HTTP/1.1\r\nhost: app28070547.sb02.stations.graphenedb.com:24789\r\nauthorization: Basic YXBwMjgwNzA1NDc6cTM4UGx4UlFPckdQN1N5RVplS2k=\r\naccept: application/json\r\ncontent-length: 770\r\nConnection: keep-alive\r\n\r\n',
        _hasBody: true,
        _trailer: '',
        finished: true,
        _hangupClose: false,
        socket: [Object],
        connection: [Object],
        agent: [Object],
        socketPath: undefined,
        method: 'POST',
        path: '/db/data/batch',
        _headers: [Object],
        _headerNames: [Object],
        parser: null,
        res: [Circular] },
     ntick: true,
     response: [Circular],
     _destdata: true,
     _ended: true,
     _callbackCalled: true },
  toJSON: [Function: toJSON],
  body: 
   [ { id: 0, body: [Object], from: '/cypher?includeStats=true' },
     { id: 1, body: [Object], from: '/cypher?includeStats=true' } ] }